version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "vasconcel"
    assignees:
      - "vasconcel"
    groups:
      python-dependencies:
        patterns:
          - "*"