name: CI/CD Workflow

on:
  workflow_run:
    workflows: 
      - Continuous Integration Lint
      - Continuous Integration Tests
    types:
      - completed

jobs:
  merge-check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Log conclusion
    run: |
      echo "Workflow conclusion result: ${{ github.event.workflow_run.conclusion }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify if the token is set
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "Token is not set!"
            exit 1
          else
            echo "Token is set."
          fi
      
      - name: Verify Success of Lint and Tests
        run: |
          echo "Lint e testes completados com sucesso. O código está pronto para revisão e merge."
      
      - name: Create Pull Request from feature branch to develop
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated PR: Merge feature/* into develop"
          body: "Este PR foi automaticamente criado após a conclusão bem-sucedida dos workflows de lint e testes."
          base: develop
          branch: ${{ github.head_ref }}
          draft: false
