name: Continuous Deployment to PythonAnywhere

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium --with-deps

      - name: Execute Deploy & Reload
        env:
          PYTHONANYWHERE_USERNAME: "datawashes"
          PYTHONANYWHERE_PASSWORD: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
        run: python scripts/deploy_pythonanywhere.py
