name: Continuous Integration Lint

on:
  push:
    branches: 
      - feature/*
  pull_request:
    branches: 
      - develop

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and install dependencies
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint and save output
        id: pylint
        run: |
          pylint $(find . -name "*.py") || true

      - name: Upload Lint Results
        uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: validation_pylint.txt