name: Continuous Integration Tests

on:
  push:
    branches:
      - feature/*
#  pull_request:
#    branches:
#      - develop

jobs:
  build-execute-test:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'

          - name: Install ODBC and SQL Server drivers
            run: |
              sudo apt-get update
              sudo apt-get install unixodbc unixodbc-dev
              sudo ACCEPT_EULA=Y apt-get -y install msodbcsql17

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Start API server
            run: |
              python src/app.py &  
              sleep 5

          - name: Run tests
            id: running-test
            run: |
              python -m pytest -v