name: Continuos Integration

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-execute-test:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up Python 
            uses: actions/setup-python@v3
            with:
              python-version: '3.10'
            
          - name: Install ODBC and SQL Server drivers
            run: |
              sudo apt-get update
              sudo apt-get install unixodbc unixodbc-dev
              sudo apt-get install msodbcsql17

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              
          - name: Start API server
            run: |
              python src/app.py &  
              sleep 5
              
          - name: Run tests
            run: |
              python -m pytest -v
            
            



